- name: Ensure Caddy is installed
  stat:
    path: "/etc/caddy/Caddyfile"
  register: caddy_config_file

- name: Install Caddy manually
  become: true
  shell: |
    sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
    sudo apt update
    sudo apt install caddy
  when: not caddy_config_file.stat.exists

- name: Set group permissions for caddy user 
  become: true
  shell: |
    sudo usermod -a -G ubuntu caddy

- name: Install caddy package (caddy-transform)
  shell: sudo caddy add-package github.com/caddyserver/transform-encoder
  become: yes
  become_user: root
  ignore_errors: yes

- name: Copy templated Caddyfile to /etc/caddy/Caddyfile
  template:
    src: project_configs/Caddyfile.j2
    dest: /etc/caddy/Caddyfile
  become: yes
  become_user: root

- name: Restart caddy
  ansible.builtin.systemd:
    daemon_reload: true
    name: caddy
    state: restarted
  become: yes
  become_user: root

- name: Reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
  become: yes
  become_user: root
