---
- hosts: infra-manager-main
  gather_facts: true

  vars:
    rbenv:
      env: user
      version: v1.2.0
      default_ruby: 3.2.2
      rubies:
      - version: 3.2.2

  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: ubuntu
    - role: gantsign.golang
      golang_gopath: '$HOME/go'

  tasks:
    - include_vars: "credentials.yaml"
      tags: [ always, bootstrap, postgresql, caddy, rails, anycable ]

    - include_vars: "credentials_for_github.yaml"
      tags: [ always, bootstrap, postgresql, caddy, rails, anycable ]

    - name: Add SSH Configuration file
      copy:
        src: "ssh-config"
        dest: "/home/ubuntu/.ssh/config"
        mode: 0440

    - name: Check if capistrano is already setup
      stat:
        path: "/home/ubuntu/problog-backend"
      register: deployed_app_path

    - name: Register github deploy key
      uri:
        url: https://api.github.com/repos/{{ github_deploy_key_owner }}/{{ github_deploy_key_repository }}/keys
        method: POST
        body: "{'key': '{{ lookup('file', 'problog.pub') }}', 'title': '{{ github_deploy_key_repository }}-key', 'read_only': true }"
        body_format: json
        status_code: [201, 422]
        headers:
          Accept: application/vnd.github+json
          Authorization: Bearer {{ github_deploy_key_token }}
      tags: [ bootstrap ]

    - name: Register github deploy key for toss-payments-ruby
      uri:
        url: https://api.github.com/repos/{{ github_deploy_key_owner }}/toss-payments-ruby/keys
        method: POST
        body: "{'key': '{{ lookup('file', 'toss_payments.pub') }}', 'title': 'toss-payments-ruby-key', 'read_only': true }"
        body_format: json
        status_code: [201, 422]
        headers:
          Accept: application/vnd.github+json
          Authorization: Bearer {{ github_deploy_key_token }}
      tags: [ bootstrap, always ]

    - name: Register github deploy key for wordpress related script
      uri:
        url: https://api.github.com/repos/{{ github_deploy_key_owner }}/infra-wordpress-docean/keys
        method: POST
        body: "{'key': '{{ lookup('file', 'wordpress.pub') }}', 'title': 'wordpress-infra-key', 'read_only': true }"
        body_format: json
        status_code: [201, 422]
        headers:
          Accept: application/vnd.github+json
          Authorization: Bearer {{ github_deploy_key_token }}
      tags: [ bootstrap ]

    - name: ping
      ping:
      tags: [ always, bootstrap ]

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes
      become: true
      tags: [ bootstrap ]

    - name: Check if a reboot is needed for Ubuntu server
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no
      tags: [ bootstrap ]

    - name: Reboot the Ubuntu server
      reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
      become: true
      tags: [ bootstrap ]

    - name: node setup
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      tags: [ bootstrap, node ]

    - name: Setup key-ring for yarn
      shell: |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      tags: [ bootstrap, node ]

    - name: Register yarn repository to sources.list.d
      shell: |
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      tags: [ bootstrap, node ]

    - name: install packages
      apt:
        pkg:
          - zlib1g-dev
          - build-essential
          - libssl-dev
          - libreadline-dev
          - libyaml-dev
          - libsqlite3-dev
          - sqlite3
          - libxml2-dev
          - libxslt1-dev
          - libcurl4-openssl-dev
          - software-properties-common
          - libffi-dev
          - nodejs
          - yarn
          - checkinstall
          - zlib1g-dev
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - python3-pip
          - python3-psycopg2
          - python-is-python3
          - python2
        update_cache: yes
        state: latest
      become: true
      tags: [ bootstrap, dependencies ]
      ignore_errors: yes

    - name: install packages again
      apt:
        pkg:
          - zlib1g-dev
          - build-essential
          - libssl-dev
          - libreadline-dev
          - libyaml-dev
          - libsqlite3-dev
          - sqlite3
          - libxml2-dev
          - libxslt1-dev
          - libcurl4-openssl-dev
          - software-properties-common
          - libffi-dev
          - nodejs
          - yarn
          - checkinstall
          - zlib1g-dev
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - python3-pip
          - python3-psycopg2
          - python-is-python3
          - python2
        update_cache: yes
        state: latest
      become: true
      tags: [ bootstrap, dependencies ]

    - name: Setup rbenv
      include_role:
        name: zzet.rbenv
        apply:
          tags: [ bootstrap, rails ]
      vars:
        rbenv_users:
          - ubuntu
      tags: [ bootstrap, rails ]

    - name: Setup postgresql
      include_tasks:
        file: postgres.yaml
        apply:
          vars:
            db_password: "{{ postgres_root_password }}"
          tags: [ bootstrap, postgresql ]
      tags: [ bootstrap, postgresql ]

    - name: add rbenv initialization to zsh profile
      blockinfile:
        block: "{{lookup('file', 'rbenv.sh')}}"
        dest: ~/.zshrc
      tags: [ bootstrap, rails ]

    - name: Install ansible
      shell: |
        sudo apt update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt-get install -y ansible

      become: true
      tags: [ provisioning ]

    - name: Install terraform
      shell: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common

        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

        gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

        sudo apt update
        sudo apt-get install terraform

      become: true
      tags: [ provisioning ]

    - name: Setup Anycable
      include_tasks:
        file: anycable.yaml
        apply:
          tags: [ rails, anycable ]
      tags: [ rails, anycable ]

    - name: Deploy rails app
      block:
      - name: Setup rails
        include_tasks:
          file: rails.yaml
          apply:
            tags: [ booystrap, rails, install-only ]
      rescue:
      - name: Check if capistrano is already setup
        stat:
          path: "/home/ubuntu/problog-backend"
        register: deployed_app_path

      - name: "copy rails database.yml file to share folder"
        template:
          src: "project_configs/database.yml.j2"
          dest: "/home/ubuntu/problog-backend/shared/config/database.yml"
        when: deployed_app_path.stat.exists

      - name: "copy rails credential key file to share folder"
        copy:
          src: "project_configs/production.key"
          dest: "/home/ubuntu/problog-backend/shared/config/credentials/"
        when: deployed_app_path.stat.exists

      - name: Setup caddy web server
        include_tasks:
          file: caddy.yaml
          apply:
            tags: [ bootstrap, caddy, anycable ]
        tags: [ bootstrap, caddy, anycable ]

      - name: Setup rails
        include_tasks:
          file: rails.yaml
          apply:
            tags: [ booystrap, rails, install-only ]
      tags: [ bootstrap, rails, install-only, caddy, anycable ]

