
- name: Clone rails project from remote 
  local_action:
    module: shell
    cmd: rm -rf problog-backend && git clone git@github.com:TeamMilestone/problog-backend
    chdir: /tmp

- name: "Deploy rails project using capistrano"
  local_action:
    module: shell
    cmd: bundle exec cap production deploy
    chdir: /tmp/problog-backend

- name: Set permissions for directories
  shell: "/usr/bin/find /home/ubuntu/problog-backend -type d -exec chmod 750 {} \\;"

- name: Set permissions for files
  # for executable files
  shell: "/usr/bin/find /home/ubuntu/problog-backend -type f -exec chmod 740 {} \\;"

- name: 
  ansible.builtin.file:
    path: /home/ubuntu/problog-backend/shared/log/caddy.log
    owner: ubuntu
    group: ubuntu
    state: touch
    mode: u=rwx,g=rw,o=r

